server:
  connectionTimeout: -1
  port: ${your.server.port}
  servlet:
    context-path: /vk-chat-bot
api:
  vk:
    url: https://api.vk.com/method/
    version: ${your.version.vk.api}

token:
  confirmation:  ${your.confirmation.token}
  access: ${your.access.token}


secret:
  key: ${your.secret.key}


